import { 
  WorkOrder, 
  Asset, 
  Location, 
  Vendor, 
  InventoryItem, 
  PreventiveMaintenance,
  ServiceRequest,
  User
} from '../../../types/common.types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Chen',
    firstName: 'Sarah',
    lastName: 'Chen',
    email: 'sarah.chen@company.com',
    role: 'facility_manager',
    avatar: '/avatars/sarah.jpg',
    department: 'Operations',
    phone: '+1 (555) 123-4567',
    createdAt: new Date('2023-01-15')
  },
  {
    id: 'user-2',
    name: 'Mike Rodriguez',
    firstName: 'Mike',
    lastName: 'Rodriguez',
    email: 'mike.r@company.com',
    role: 'technician',
    department: 'Maintenance',
    phone: '+1 (555) 234-5678',
    createdAt: new Date('2023-03-20')
  },
  {
    id: 'user-3',
    name: 'Emily Watson',
    firstName: 'Emily',
    lastName: 'Watson',
    email: 'emily.w@company.com',
    role: 'finance',
    department: 'Finance',
    phone: '+1 (555) 345-6789',
    createdAt: new Date('2023-02-10')
  },
]

// Mock Work Orders
export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'WO-2024-001',
    title: 'HVAC System Failure - Building A',
    description: 'Main HVAC unit on 3rd floor not cooling properly. Temperature readings show 78°F when set to 68°F.',
    status: 'in_progress',
    priority: 'critical',
    type: 'reactive',
    category: 'HVAC',
    locationId: 'loc-3',
    locationName: 'Building A - Floor 3',
    assetId: 'asset-1',
    assetName: 'Carrier HVAC Unit #A3-01',
    assigneeId: 'user-2',
    assigneeName: 'Mike Rodriguez',
    requesterId: 'user-1',
    requesterName: 'Sarah Chen',
    dueDate: new Date('2024-01-20'),
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-19'),
    estimatedCost: 2500,
    actualCost: 1800,
  },
  {
    id: 'WO-2024-002',
    title: 'Elevator Maintenance Required',
    description: 'Annual elevator inspection and maintenance due. Elevator #2 showing intermittent door issues.',
    status: 'open',
    priority: 'high',
    category: 'Elevator',
    locationId: 'loc-1',
    type: 'inspection',
    locationName: 'Main Building - Lobby',
    assetId: 'asset-2',
    assetName: 'Otis Elevator #2',
    assigneeId: 'vendor-2',
    assigneeName: 'Elevator Solutions Inc',
    requesterId: 'user-1',
    requesterName: 'Sarah Chen',
    dueDate: new Date('2024-01-25'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    estimatedCost: 5000,
  },
  {
    id: 'WO-2024-003',
    title: 'Broken Window - Conference Room B',
    description: 'Large crack in window pane of Conference Room B. Safety hazard - needs immediate replacement.',
    status: 'open', // Changed from 'pending' to 'open'
    priority: 'high',
    category: 'Structural',
    locationId: 'loc-4',
    type: 'emergency',
    locationName: 'Building B - Floor 2',
    requesterId: 'user-1',
    requesterName: 'Sarah Chen',
    dueDate: new Date('2024-01-22'),
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-18'),
    estimatedCost: 800,
  },
  {
    id: 'WO-2024-004',
    title: 'Plumbing Leak - Restroom',
    description: 'Water leak under sink in men\'s restroom on floor 1. Water damage visible on cabinet.',
    status: 'completed',
    priority: 'medium',
    category: 'Plumbing',
    type: 'reactive',
    locationId: 'loc-2',
    locationName: 'Building A - Floor 1',
    assigneeId: 'user-2',
    assigneeName: 'Mike Rodriguez',
    requesterId: 'user-1',
    requesterName: 'Sarah Chen',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-12'),
    estimatedCost: 350,
    actualCost: 275,
  },
  {
    id: 'WO-2024-005',
    title: 'Replace Light Fixtures - Hallway',
    description: 'Multiple fluorescent lights flickering in main hallway. Need to replace ballasts and tubes.',
    status: 'open',
    priority: 'low',
    category: 'Electrical',
    locationId: 'loc-2',
    type: 'inspection',
    locationName: 'Building A - Floor 1',
    assigneeId: 'vendor-1',
    assigneeName: 'ProTech HVAC Services',
    requesterId: 'user-1',
    requesterName: 'Sarah Chen',
    dueDate: new Date('2024-02-01'),
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
    estimatedCost: 450,
  },
  {
    id: 'WO-2024-006',
    title: 'Fire Alarm Testing',
    description: 'Quarterly fire alarm system testing and inspection required per safety regulations.',
    status: 'open',
    priority: 'high',
    category: 'Safety',
    type: 'inspection',
    locationId: 'loc-1',
    locationName: 'Main Building',
    requesterId: 'user-1',
    requesterName: 'Sarah Chen',
    dueDate: new Date('2024-01-30'),
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    estimatedCost: 1200,
  },
]

// Mock Assets
export const mockAssets: Asset[] = [
  {
    id: 'asset-1',
    name: 'Carrier HVAC Unit #A3-01',
    category: 'HVAC',
    model: 'Carrier 50XC',
    serialNumber: 'CAR-2019-45678',
    manufacturer: 'Carrier',
    locationId: 'loc-3',
    locationName: 'Building A - Floor 3',
    status: 'under_repair',
    installDate: new Date('2019-06-15'),
    warrantyExpiry: new Date('2024-06-15'),
    lastMaintenanceDate: new Date('2023-12-01'),
    nextMaintenanceDate: new Date('2024-03-01'),
    purchaseCost: 45000,
    currentValue: 32000,
  },
  {
    id: 'asset-2',
    name: 'Otis Elevator #2',
    category: 'Elevator',
    model: 'Otis Gen2',
    serialNumber: 'OTIS-2018-12345',
    manufacturer: 'Otis',
    locationId: 'loc-1',
    locationName: 'Main Building - Lobby',
    status: 'down',
    installDate: new Date('2018-03-20'),
    warrantyExpiry: new Date('2023-03-20'),
    lastMaintenanceDate: new Date('2023-10-15'),
    nextMaintenanceDate: new Date('2024-01-15'),
    purchaseCost: 125000,
    currentValue: 95000,
  },
  {
    id: 'asset-3',
    name: 'Emergency Generator',
    category: 'Power',
    model: 'Caterpillar C15',
    serialNumber: 'CAT-2020-98765',
    manufacturer: 'Caterpillar',
    locationId: 'loc-5',
    locationName: 'Building A - Basement',
    status: 'active',
    installDate: new Date('2020-09-01'),
    warrantyExpiry: new Date('2025-09-01'),
    lastMaintenanceDate: new Date('2024-01-05'),
    nextMaintenanceDate: new Date('2024-04-05'),
    purchaseCost: 85000,
    currentValue: 72000,
  },
  {
    id: 'asset-4',
    name: 'Boiler System',
    category: 'Heating',
    model: 'Weil-McLain 88',
    serialNumber: 'WM-2017-33456',
    manufacturer: 'Weil-McLain',
    locationId: 'loc-5',
    locationName: 'Building A - Basement',
    status: 'active',
    installDate: new Date('2017-11-10'),
    warrantyExpiry: new Date('2022-11-10'),
    lastMaintenanceDate: new Date('2023-11-15'),
    nextMaintenanceDate: new Date('2024-05-15'),
    purchaseCost: 35000,
    currentValue: 18000,
  },
  {
    id: 'asset-5',
    name: 'Security Camera System',
    category: 'Security',
    model: 'Hikvision DS-2CD2185',
    serialNumber: 'HIK-2021-77890',
    manufacturer: 'Hikvision',
    locationId: 'loc-1',
    locationName: 'Main Building',
    status: 'active',
    installDate: new Date('2021-04-22'),
    warrantyExpiry: new Date('2026-04-22'),
    lastMaintenanceDate: new Date('2023-12-20'),
    nextMaintenanceDate: new Date('2024-06-20'),
    purchaseCost: 28000,
    currentValue: 22000,
  },
]

// Mock Locations
export const mockLocations: Location[] = [
  {
    id: 'loc-1',
    name: 'Main Building',
    type: 'building',
    address: '123 Corporate Drive, Suite 100',
    assetCount: 45,
    openWorkOrders: 3,
  },
  {
    id: 'loc-2',
    name: 'Floor 1',
    type: 'floor',
    parentId: 'loc-1',
    assetCount: 15,
    openWorkOrders: 1,
  },
  {
    id: 'loc-3',
    name: 'Floor 3',
    type: 'floor',
    parentId: 'loc-1',
    assetCount: 12,
    openWorkOrders: 1,
  },
  {
    id: 'loc-4',
    name: 'Building B',
    type: 'building',
    address: '125 Corporate Drive',
    assetCount: 28,
    openWorkOrders: 1,
  },
  {
    id: 'loc-5',
    name: 'Basement',
    type: 'floor',
    parentId: 'loc-1',
    assetCount: 8,
    openWorkOrders: 0,
  },
]

// Mock Vendors
export const mockVendors: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'ProTech HVAC Services',
    category: 'HVAC',
    status: 'active',
    serviceCategories: ['HVAC Maintenance', 'HVAC Repair', 'Emergency HVAC Services'],
    email: 'service@protechhvac.com',
    phone: '+1 (555) 456-7890',
    address: '456 Service Road, Industrial Park',
    rating: 4.8,
    contractStart: new Date('2023-01-01'),
    contractEnd: new Date('2025-12-31'),
    slaDetails: '4-hour response for critical issues, 24-hour for standard',
    totalSpend: 125000,
    completedJobs: 47,
  },
  {
    id: 'vendor-2',
    name: 'Elevator Solutions Inc',
    category: 'Elevator',
    email: 'support@elevatorsolutions.com',
    phone: '+1 (555) 567-8901',
     status: 'active',
    serviceCategories: ['HVAC Maintenance', 'HVAC Repair', 'Emergency HVAC Services'],
    address: '789 Vertical Ave',
    rating: 4.5,
    contractStart: new Date('2022-06-01'),
    contractEnd: new Date('2024-05-31'),
    slaDetails: '2-hour response for entrapment, 8-hour for other issues',
    totalSpend: 85000,
    completedJobs: 23,
  },
  {
    id: 'vendor-3',
    name: 'SafeGuard Security',
    category: 'Security',
    email: 'contracts@safeguardsec.com',
    phone: '+1 (555) 678-9012',
    address: '321 Protection Blvd',
     status: 'active',
    serviceCategories: ['HVAC Maintenance', 'HVAC Repair', 'Emergency HVAC Services'],
    rating: 4.9,
    contractStart: new Date('2023-04-01'),
    contractEnd: new Date('2026-03-31'),
    slaDetails: '1-hour response for security incidents',
    totalSpend: 45000,
    completedJobs: 15,
  },
  {
    id: 'vendor-4',
    name: 'CleanPro Janitorial',
    category: 'Cleaning',
    email: 'service@cleanpro.com',
    phone: '+1 (555) 789-0123',
     status: 'active',
    serviceCategories: ['HVAC Maintenance', 'HVAC Repair', 'Emergency HVAC Services'],
    address: '654 Spotless Lane',
    rating: 4.2,
    contractStart: new Date('2023-01-01'),
    contractEnd: new Date('2024-12-31'),
    totalSpend: 96000,
    completedJobs: 365,
  },
]

// Mock Inventory
export const mockInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'HVAC Air Filter 20x25x1',
    sku: 'HVAC-FLT-2025',
    category: 'HVAC',
    quantity: 45,
    minStock: 20,
    unitPrice: 12.50,
    locationId: 'loc-5',
    locationName: 'Main Storage',
    lastRestocked: new Date('2024-01-10'),
    supplier: 'FilterPro Supply',
  },
  {
    id: 'inv-2',
    name: 'LED Light Bulb 60W',
    sku: 'ELEC-LED-60',
    category: 'Electrical',
    quantity: 5, // Triggering Low Stock Alert (minStock is 25)
    minStock: 25,
    unitPrice: 8.99,
    locationId: 'loc-5',
    locationName: 'Main Storage',
    lastRestocked: new Date('2023-12-15'),
    supplier: 'LightWorld',
  },
  {
    id: 'inv-3',
    name: 'Plumbing Pipe Fitting 3/4"',
    sku: 'PLMB-FIT-075',
    category: 'Plumbing',
    quantity: 120,
    minStock: 50,
    unitPrice: 3.25,
    locationId: 'loc-5',
    locationName: 'Main Storage',
    lastRestocked: new Date('2024-01-05'),
    supplier: 'PlumbMaster',
  },
  {
    id: 'inv-4',
    name: 'Fire Extinguisher 10lb',
    sku: 'SAFE-FEX-10',
    category: 'Safety',
    quantity: 15,
    minStock: 10,
    unitPrice: 45.00,
    locationId: 'loc-5',
    locationName: 'Main Storage',
    lastRestocked: new Date('2023-11-20'),
    supplier: 'SafetyFirst',
  },
  {
    id: 'inv-5',
    name: 'Door Lock Cylinder',
    sku: 'SECU-LCK-01',
    category: 'Security',
    quantity: 5,
    minStock: 10,
    unitPrice: 28.50,
    locationId: 'loc-5',
    locationName: 'Main Storage',
    lastRestocked: new Date('2023-10-30'),
    supplier: 'LockSmart',
  },
]

// Mock Preventive Maintenance
export const mockPMs: PreventiveMaintenance[] = [
  {
    id: "pm-1",
    title: "HVAC Quarterly Filter Change",
    description: "Replace all HVAC filters and inspect belts",
    assetId: "asset-1",
    locationId: "loc-5",
    locationName: "Main Storage",
    assetName: "Carrier HVAC Unit #A3-01",
    frequency: "quarterly",
    nextDue: new Date("2024-03-01"),
    lastCompleted: new Date("2023-12-01"),
    assigneeId: "user-2",
    assigneeName: "Mike Rodriguez",
    checklist: [
      { id: "ck-1", text: "Replace air filters", isCompleted: false },
      { id: "ck-2", text: "Inspect belt tension", isCompleted: false },
      { id: "ck-3", text: "Clean condenser coils", isCompleted: false },
      { id: "ck-4", text: "Check refrigerant levels", isCompleted: false },
    ],
    isActive: true,
  },
  {
    id: "pm-2",
    title: "Elevator Monthly Inspection",
    description: "Monthly safety inspection and lubrication",
    assetId: "asset-2",
    locationId: "loc-5",
    locationName: "Main Storage",
    assetName: "Otis Elevator #2",
    frequency: "monthly",
    nextDue: new Date("2024-02-01"),
    lastCompleted: new Date("2024-01-01"),
    checklist: [
      { id: "ck-5", text: "Test emergency stop", isCompleted: false },
      { id: "ck-6", text: "Lubricate door tracks", isCompleted: false },
      { id: "ck-7", text: "Check safety sensors", isCompleted: false },
    ],
    isActive: true,
  },
  {
    id: "pm-3",
    title: "Generator Weekly Test",
    description: "Weekly generator test run and inspection",
    assetId: "asset-3",
    locationId: "loc-5",
    locationName: "Main Storage",
    assetName: "Emergency Generator",
    frequency: "weekly",
    nextDue: new Date("2024-01-26"),
    lastCompleted: new Date("2024-01-19"),
    assigneeId: "user-2",
    assigneeName: "Mike Rodriguez",
    checklist: [
      { id: "ck-8", text: "Run generator for 30 minutes", isCompleted: false },
      { id: "ck-9", text: "Check oil level", isCompleted: false },
      { id: "ck-10", text: "Inspect fuel level", isCompleted: false },
    ],
    isActive: true,
  },
];

// Mock Service Requests
export const mockServiceRequests: ServiceRequest[] = [
  {
    id: 'sr-1',
    title: 'AC Not Working in Office 302',
    description: 'The air conditioning in my office has been blowing warm air since this morning.',
    category: 'HVAC',
    status: 'in_progress',
    priority: 'high',
    requesterId: 'staff-1',
    requesterName: 'John Smith',
    requesterEmail: 'john.smith@company.com',
    locationId: 'loc-3',
    locationName: 'Building A - Floor 3 - Office 302',
    createdAt: new Date('2024-01-19'),
  },
  {
    id: 'sr-2',
    title: 'Light Flickering in Meeting Room',
    description: 'The overhead lights in Meeting Room B keep flickering during presentations.',
    category: 'Electrical',
    status: 'submitted',
    priority: 'medium',
    requesterId: 'staff-2',
    requesterName: 'Lisa Johnson',
    requesterEmail: 'lisa.j@company.com',
    locationId: 'loc-4',
    locationName: 'Building B - Floor 2 - Meeting Room B',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'sr-3',
    title: 'Broken Chair in Cafeteria',
    description: 'One of the chairs in the cafeteria has a broken leg and is unsafe to use.',
    category: 'Furniture',
    status: 'resolved',
    priority: 'low',
    requesterId: 'staff-3',
    requesterName: 'David Lee',
    requesterEmail: 'david.lee@company.com',
    locationId: 'loc-2',
    locationName: 'Building A - Floor 1 - Cafeteria',
    createdAt: new Date('2024-01-15'),
    resolvedAt: new Date('2024-01-16'),
    rating: 5,
    feedback: 'Quick response and fixed promptly!',
  },
]

// Dashboard Statistics
export const dashboardStats = {
  totalWorkOrders: 156,
  openWorkOrders: 23,
  completedThisMonth: 42,
  dueToday: 3,
  completedThisWeek: 12,
  overdueWorkOrders: 5,
  pmCompliance: 94,
  avgResponseTime: '2.3 hrs',
  totalAssets: 245,
  assetsNeedingMaintenance: 12,
  monthlySpend: 45680,
  budgetUtilization: 72,
  vendorCount: 18,
  avgVendorRating: 4.5,
}

// Chart Data
export const workOrderTrendData = [
  { month: 'Aug', created: 45, completed: 42 },
  { month: 'Sep', created: 52, completed: 48 },
  { month: 'Oct', created: 38, completed: 41 },
  { month: 'Nov', created: 61, completed: 55 },
  { month: 'Dec', created: 47, completed: 52 },
  { month: 'Jan', created: 56, completed: 42 },
]

export const categoryBreakdownData = [
  { name: 'HVAC', value: 28, fill: 'var(--chart-1)' },
  { name: 'Electrical', value: 22, fill: 'var(--chart-2)' },
  { name: 'Plumbing', value: 18, fill: 'var(--chart-3)' },
  { name: 'Elevator', value: 12, fill: 'var(--chart-4)' },
  { name: 'Other', value: 20, fill: 'var(--chart-5)' },
]

export const costByMonthData = [
  { month: 'Aug', cost: 38500 },
  { month: 'Sep', cost: 42300 },
  { month: 'Oct', cost: 35800 },
  { month: 'Nov', cost: 51200 },
  { month: 'Dec', cost: 48900 },
  { month: 'Jan', cost: 45680 },
]

// ─── Extended mock data for new features ─────────────────────────────────────
// import type { ServiceRequest, Location, Vendor, InventoryItem, Asset, PreventiveMaintenance } from '@/types/common.types'

// export const mockServiceRequests: ServiceRequest[] = [
//   { id: 'SR-001', title: 'AC not cooling in Room 302', description: 'The AC unit in room 302 has stopped cooling. It is very hot and affecting work.', category: 'HVAC', status: 'in_progress', priority: 'high', requesterId: 'u5', requesterName: 'John Taylor', requesterEmail: 'john@corp.com', locationId: 'l3', locationName: 'Floor 3 - Room 302', createdAt: new Date('2024-12-10'), images: [] },
//   { id: 'SR-002', title: 'Water leak under sink - Kitchen', description: 'There is a slow drip under the kitchen sink. Water pooling on the floor.', category: 'Plumbing', status: 'submitted', priority: 'medium', requesterId: 'u6', requesterName: 'Alice Brown', requesterEmail: 'alice@corp.com', locationId: 'l2', locationName: 'Building A - Kitchen', createdAt: new Date('2024-12-12'), images: [] },
//   { id: 'SR-003', title: 'Elevator making grinding noise', description: 'Elevator 2 is making a loud grinding noise when stopping at floors. Concerned about safety.', category: 'Elevators', status: 'approved', priority: 'critical', requesterId: 'u7', requesterName: 'Bob Smith', requesterEmail: 'bob@corp.com', locationId: 'l1', locationName: 'Main Building - Elevator Lobby', createdAt: new Date('2024-12-13'), images: [] },
//   { id: 'SR-004', title: 'Broken light in parking lot', description: 'Three lights in the north parking lot are out. Safety hazard at night.', category: 'Electrical', status: 'resolved', priority: 'medium', requesterId: 'u5', requesterName: 'John Taylor', requesterEmail: 'john@corp.com', locationId: 'l4', locationName: 'North Parking Lot', createdAt: new Date('2024-12-05'), resolvedAt: new Date('2024-12-07'), rating: 4, feedback: 'Fixed quickly, thank you!' },
//   { id: 'SR-005', title: 'Pest sighting in storage room B', description: 'Saw several cockroaches in storage room B near the east wing. Need urgent pest control.', category: 'Pest Control', status: 'reviewed', priority: 'high', requesterId: 'u6', requesterName: 'Alice Brown', requesterEmail: 'alice@corp.com', locationId: 'l5', locationName: 'East Wing - Storage Room B', createdAt: new Date('2024-12-14'), images: [] },
// ]

// export const mockVendors: Vendor[] = [
//   { id: 'v1', name: 'CoolTech HVAC Services', category: 'HVAC', serviceCategories: ['HVAC','Electrical'], email: 'info@cooltech.com', phone: '+1-555-010-1020', rating: 4.5, status: 'active', contractStart: new Date('2024-01-01'), contractEnd: new Date('2025-01-31'), contractValue: 48000, slaResponseTime: 2, slaResolutionTime: 8, totalSpend: 32400, completedJobs: 28, pendingJobs: 2, contactPerson: 'David Lee', address: '100 Industrial Ave', insuranceExpiry: new Date('2025-06-30') },
//   { id: 'v2', name: 'AquaFix Plumbing', category: 'Plumbing', serviceCategories: ['Plumbing','Sewage'], email: 'service@aquafix.com', phone: '+1-555-020-2030', rating: 4.2, status: 'active', contractStart: new Date('2024-03-01'), contractEnd: new Date('2025-03-31'), contractValue: 24000, slaResponseTime: 3, slaResolutionTime: 12, totalSpend: 18700, completedJobs: 19, pendingJobs: 1, contactPerson: 'Maria Santos' },
//   { id: 'v3', name: 'PestAway Services', category: 'Pest Control', serviceCategories: ['Pest Control'], email: 'ops@pestaway.com', phone: '+1-555-030-3040', rating: 4.0, status: 'active', contractStart: new Date('2024-06-01'), contractEnd: new Date('2024-12-31'), contractValue: 12000, totalSpend: 9800, completedJobs: 12, pendingJobs: 0 },
//   { id: 'v4', name: 'SafeGuard Fire Protection', category: 'Fire Safety', serviceCategories: ['Fire Safety'], email: 'info@safeguard.com', phone: '+1-555-040-4050', rating: 4.8, status: 'active', contractStart: new Date('2024-01-01'), contractEnd: new Date('2025-12-31'), contractValue: 36000, totalSpend: 28000, completedJobs: 22, pendingJobs: 1 },
//   { id: 'v5', name: 'CleanPro Janitorial', category: 'Cleaning', serviceCategories: ['Cleaning'], email: 'hello@cleanpro.com', phone: '+1-555-050-5060', rating: 3.8, status: 'active', contractStart: new Date('2024-02-01'), contractEnd: new Date('2025-02-28'), contractValue: 60000, totalSpend: 52000, completedJobs: 180, pendingJobs: 0 },
//   { id: 'v6', name: 'ElectroPro Contractors', category: 'Electrical', serviceCategories: ['Electrical','Security'], email: 'work@electropro.com', phone: '+1-555-060-6070', rating: 4.3, status: 'inactive', totalSpend: 8200, completedJobs: 8, pendingJobs: 0 },
// ]

// export const mockInventory: InventoryItem[] = [
//   { id: 'i1', name: 'HVAC Air Filters 16x20x1', sku: 'AF-16X20-001', category: 'HVAC', description: 'Standard pleated air filter, MERV 8', quantity: 3, minStock: 10, maxStock: 50, unitPrice: 8.99, unit: 'piece', locationId: 'l1', locationName: 'Main Storeroom', lastRestocked: new Date('2024-11-01'), supplier: 'Grainger' },
//   { id: 'i2', name: 'Refrigerant R-410A (25lb)', sku: 'REF-R410A-25', category: 'HVAC', quantity: 2, minStock: 2, maxStock: 8, unitPrice: 185, unit: 'cylinder', locationId: 'l1', locationName: 'Main Storeroom', supplier: 'Johnstone Supply' },
//   { id: 'i3', name: 'Circuit Breaker 20A', sku: 'CB-20A-SQRD', category: 'Electrical', quantity: 12, minStock: 5, maxStock: 30, unitPrice: 42.50, unit: 'piece', locationId: 'l1', locationName: 'Main Storeroom' },
//   { id: 'i4', name: 'PVC Pipe 1" x 10ft', sku: 'PVC-1IN-10FT', category: 'Plumbing', quantity: 8, minStock: 4, maxStock: 20, unitPrice: 12.75, unit: 'piece', locationId: 'l2', locationName: 'Building B Storeroom' },
//   { id: 'i5', name: 'Fire Extinguisher 5lb ABC', sku: 'FE-5LB-ABC', category: 'Fire Safety', quantity: 4, minStock: 5, maxStock: 15, unitPrice: 62, unit: 'piece', locationId: 'l1', locationName: 'Main Storeroom' },
//   { id: 'i6', name: 'LED Bulb E26 9W', sku: 'LED-E26-9W', category: 'Electrical', quantity: 45, minStock: 20, maxStock: 100, unitPrice: 4.25, unit: 'piece', locationId: 'l1', locationName: 'Main Storeroom', lastRestocked: new Date('2024-11-15') },
//   { id: 'i7', name: 'Drain Cleaner (1 Gallon)', sku: 'DC-1GAL-PRO', category: 'Plumbing', quantity: 0, minStock: 3, maxStock: 12, unitPrice: 28.99, unit: 'gallon', locationId: 'l2', locationName: 'Building B Storeroom' },
//   { id: 'i8', name: 'Elevator Hydraulic Fluid', sku: 'EHF-ISO46-5G', category: 'Elevator', quantity: 2, minStock: 1, maxStock: 6, unitPrice: 124.50, unit: 'bucket', locationId: 'l1', locationName: 'Main Storeroom' },
// ]

// export const mockUsers = [
//   { id: 'u1', name: 'Sarah Chen', email: 'sarah@corp.com', role: 'facility_manager' as const, phone: '+1-555-100-1001' },
//   { id: 'u2', name: 'Mike Rodriguez', email: 'mike@corp.com', role: 'technician' as const, phone: '+1-555-100-1002' },
//   { id: 'u3', name: 'Emma Wilson', email: 'emma@corp.com', role: 'technician' as const, phone: '+1-555-100-1003' },
//   { id: 'u4', name: 'James Park', email: 'james@corp.com', role: 'admin' as const, phone: '+1-555-100-1004' },
//   { id: 'u5', name: 'Lisa Chen', email: 'lisa@corp.com', role: 'finance' as const, phone: '+1-555-100-1005' },
// ]
