const API_BASE = '/api/v1'

export const ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_BASE}/auth/login`, REGISTER_ORGANIZATION: `${API_BASE}/auth/register/organization`, REGISTER_VENDOR: `${API_BASE}/auth/register/vendor`,
    LOGOUT: `${API_BASE}/auth/logout`, FORGOT_PASSWORD: `${API_BASE}/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE}/auth/reset-password`, ME: `${API_BASE}/auth/me`,
    CHANGE_PASSWORD: `${API_BASE}/auth/change-password`,
  },
  WORK_ORDERS: {
    LIST: `${API_BASE}/work-orders`, CREATE: `${API_BASE}/work-orders`,
    VENDOR_ASSIGNED: `${API_BASE}/work-orders/vendor/assigned`,
    DETAIL: (id: string) => `${API_BASE}/work-orders/${id}`,
    UPDATE: (id: string) => `${API_BASE}/work-orders/${id}`,
    DELETE: (id: string) => `${API_BASE}/work-orders/${id}`,
    ASSIGN: (id: string) => `${API_BASE}/work-orders/${id}/assign`,
    VENDOR_CANDIDATES: (id: string) => `${API_BASE}/work-orders/${id}/vendor-candidates`,
    TECHNICIAN_CANDIDATES: (id: string) => `${API_BASE}/work-orders/${id}/technician-candidates`,
    TRANSITION: (id: string) => `${API_BASE}/work-orders/${id}/transition`,
    COMMENTS: (id: string) => `${API_BASE}/work-orders/${id}/comments`,
    ACTIVITY: (id: string) => `${API_BASE}/work-orders/${id}/activity`,
    APPROVE: (id: string) => `${API_BASE}/work-orders/${id}/approve`,
    ATTACHMENTS: (id: string) => `${API_BASE}/work-orders/${id}/attachments`,
    PARTS: (id: string) => `${API_BASE}/work-orders/${id}/parts`,
    TIME_LOG: (id: string) => `${API_BASE}/work-orders/${id}/time-logs`,
    COMPLETION_APPROVE: (id: string) => `${API_BASE}/work-orders/${id}/completion/approve`,
    COMPLETION_REJECT: (id: string) => `${API_BASE}/work-orders/${id}/completion/reject`,
    COMPLETION_REQUEST_INFORMATION: (id: string) => `${API_BASE}/work-orders/${id}/completion/request-information`,
  },
  ASSETS: {
    LIST: `${API_BASE}/assets`, CREATE: `${API_BASE}/assets`,
    DETAIL: (id: string) => `${API_BASE}/assets/${id}`,
    UPDATE: (id: string) => `${API_BASE}/assets/${id}`,
    DELETE: (id: string) => `${API_BASE}/assets/${id}`,
    HISTORY: (id: string) => `${API_BASE}/assets/${id}/history`,
    DOCUMENTS: (id: string) => `${API_BASE}/assets/${id}/documents`,
    QR: (id: string) => `${API_BASE}/assets/${id}/qr`,
  },
  LOCATIONS: {
    LIST: `${API_BASE}/locations`, CREATE: `${API_BASE}/locations`,
    DETAIL: (id: string) => `${API_BASE}/locations/${id}`,
    UPDATE: (id: string) => `${API_BASE}/locations/${id}`,
    DELETE: (id: string) => `${API_BASE}/locations/${id}`,
    CHILDREN: (id: string) => `${API_BASE}/locations/${id}/children`,
    FLOOR_PLAN: (id: string) => `${API_BASE}/locations/${id}/floor-plan`,
  },
  VENDORS: {
    LIST: `${API_BASE}/vendors`, CREATE: `${API_BASE}/vendors`,
    DETAIL: (id: string) => `${API_BASE}/vendors/${id}`,
    UPDATE: (id: string) => `${API_BASE}/vendors/${id}`,
    DELETE: (id: string) => `${API_BASE}/vendors/${id}`,
    PERFORMANCE: (id: string) => `${API_BASE}/vendors/${id}/performance`,
    INVOICES: (id: string) => `${API_BASE}/vendors/${id}/invoices`,
    CERTIFICATIONS: (id: string) => `${API_BASE}/vendors/${id}/certifications`,
    CONTRACTS: (id: string) => `${API_BASE}/vendors/${id}/contracts`,
  },
  ORGANIZATION_VENDORS: { LIST: `${API_BASE}/organizations/me/vendors`, DETAIL: (id: string) => `${API_BASE}/organizations/me/vendors/${id}`, PERFORMANCE: (id: string) => `${API_BASE}/organizations/me/vendors/${id}/performance`, STATUS: (id: string) => `${API_BASE}/organizations/me/vendors/${id}/status` },
  CONTRACT_AWARDS: { RENEW: (id: string) => `${API_BASE}/contract-awards/${id}/renew` },
  INVOICES: { LIST: `${API_BASE}/invoices`, REVIEW: (id: string) => `${API_BASE}/invoices/${id}/review`, MARK_PAID: (id: string) => `${API_BASE}/invoices/${id}/paid` },
  INVENTORY: {
    ITEMS: `${API_BASE}/inventory/items`, BALANCES: `${API_BASE}/inventory/balances`,
    LIST: `${API_BASE}/inventory`, CREATE: `${API_BASE}/inventory`,
    DETAIL: (id: string) => `${API_BASE}/inventory/${id}`,
    UPDATE: (id: string) => `${API_BASE}/inventory/${id}`,
    DELETE: (id: string) => `${API_BASE}/inventory/${id}`,
    RECEIVE: (id: string) => `${API_BASE}/inventory/${id}/receive`,
    PURCHASE_REQUESTS: `${API_BASE}/inventory/purchase-requests`,
    BULK_IMPORT: `${API_BASE}/inventory/bulk-import`,
  },
  PM: {
    LIST: `${API_BASE}/preventive-maintenance`, CREATE: `${API_BASE}/preventive-maintenance`,
    DETAIL: (id: string) => `${API_BASE}/preventive-maintenance/${id}`,
    UPDATE: (id: string) => `${API_BASE}/preventive-maintenance/${id}`,
    DELETE: (id: string) => `${API_BASE}/preventive-maintenance/${id}`,
    COMPLETE: (id: string) => `${API_BASE}/preventive-maintenance/${id}/complete`,
    SKIP: (id: string) => `${API_BASE}/preventive-maintenance/${id}/skip`,
    CALENDAR: `${API_BASE}/preventive-maintenance/calendar`,
    COMPLIANCE: `${API_BASE}/preventive-maintenance/compliance`,
  },
  SERVICE_REQUESTS: {
    LIST: `${API_BASE}/service-requests`, CREATE: `${API_BASE}/service-requests`,
    PUBLIC: `${API_BASE}/service-requests/public`,
    DETAIL: (id: string) => `${API_BASE}/service-requests/${id}`,
    UPDATE: (id: string) => `${API_BASE}/service-requests/${id}`,
    CONVERT: (id: string) => `${API_BASE}/service-requests/${id}/convert`,
    RATE: (id: string) => `${API_BASE}/service-requests/${id}/rate`,
    APPROVE: (id: string) => `${API_BASE}/service-requests/${id}/approve`,
    REJECT: (id: string) => `${API_BASE}/service-requests/${id}/reject`,
  },
  NOTIFICATIONS: {
    LIST: `${API_BASE}/notifications`, MARK_READ: `${API_BASE}/notifications/mark-read`,
    MARK_ALL_READ: `${API_BASE}/notifications/mark-all-read`,
    DELETE: (id: string) => `${API_BASE}/notifications/${id}`,
    PREFERENCES: `${API_BASE}/notifications/preferences`,
    ESCALATION_RULES: `${API_BASE}/notifications/escalation-rules`,
  },
  REPORTS: {
    WORK_ORDERS: `${API_BASE}/reports/work-orders`,
    PM_COMPLIANCE: `${API_BASE}/reports/pm-compliance`,
    COST_ANALYSIS: `${API_BASE}/reports/cost-analysis`,
    VENDOR_PERFORMANCE: `${API_BASE}/reports/vendor-performance`,
    ASSET_HISTORY: `${API_BASE}/reports/asset-history`,
    COMPLIANCE: `${API_BASE}/reports/compliance`,
    TECHNICIAN: `${API_BASE}/reports/technician`,
    EXPORT: `${API_BASE}/reports/export`,
  },
  SETTINGS: {
    ORGANIZATION: `${API_BASE}/settings/organization`,
    USER_ME: `${API_BASE}/settings/me`, VENDOR: `${API_BASE}/settings/vendor`,
    USERS: `${API_BASE}/settings/users`, USER: (id: string) => `${API_BASE}/settings/users/${id}`,
    INVITE_USER: `${API_BASE}/settings/users/invite`,
    ROLES: `${API_BASE}/settings/roles`, ROLE: (id: string) => `${API_BASE}/settings/roles/${id}`,
    SLA: `${API_BASE}/settings/sla`,
    WORKFLOW_RULES: `${API_BASE}/settings/workflow-rules`,
    AUDIT_LOG: `${API_BASE}/settings/audit-log`,
    BACKUP: `${API_BASE}/settings/backup`,
    INTEGRATIONS: `${API_BASE}/settings/integrations`,
  },
  INVITATIONS: {
    CREATE: `${API_BASE}/invitations`,
    LIST: `${API_BASE}/invitations`,
    DETAIL: (id: string) => `${API_BASE}/invitations/${id}`,
    RESEND: (id: string) => `${API_BASE}/invitations/${id}/resend`,
    REVOKE: (id: string) => `${API_BASE}/invitations/${id}/revoke`,
  },
  DASHBOARD: {
    STATS: `${API_BASE}/dashboard/stats`, CHARTS: `${API_BASE}/dashboard/charts`,
  },
}
